### ISSUE TITLE
level 3,20 depth

### ISSUE THREAD

**Issue by kiranmaya** [harpalnain/ZerodhaAtom#1]
did you find a way to get level 20 from websockets ?

**Comment by harpalnain** [comment]
I am not using websocket, i am able to get level 3 data withing existing
code.
Regards
Harpal

**Comment by kiranmaya** [comment]
ok,my code base is in c# , i also use selenium for login purpose , seen your code , you are grabbing values from html table ,  i have 108 stocks ,i can't use your method . can you suggest me any alternative ?

**Comment by harpalnain** [comment]
Options:
1. Subscribe kite paid api. (Best and easy)
2.Try puppeteer Node.js based web automation tool. I did not try this just
recently came to know this option. I will work on it in coming future.
3.Use selenium in C# or any another language apart from python for better
performance with multiple instance with different watchlists simultaneously.
4. Use asyncio in python to make it fater for multiple instance.

Current approach also can work but with some performance compromise, create
three instance for different watchlist.
I tested it with 50 stock in single list it takes almost 3 sec for each
tick.

**Comment by kiranmaya** [comment]
ok.Between what i don't understand ,From where those level 20 comes from ,as per kite trade docs ,188 packet length is for Full quote level 5 .i'm not seeing any  packets length greater than 188 in chrome developer tools .some received messages byte length is greater than 200,but those messages is combination of packets of different quotes instruments.

**Comment by kiranmaya** [comment]
i ran the project , it saving only tick last price  ,how it save offers and bids .

**Comment by harpalnain** [comment]
Code updated for bid and offer table saving in CSV file. Pull the latest code. As of now Performance is not Tested as per the requirement.

**Comment by kiranmaya** [comment]
i rewrote your steps in c# win forms ,successfully crawling data ,  difference is ,in first loop i open all depth and did't closed it ,and second loop ,grabbed the data , this way grabbing is very fast ,able to grab 11 stocks @ 200 milliseconds ,and C# variant of selenium unable to grab in headless mode. so i have to run it in seperate desktop .
still i don't like this approach , any chance of finding source of depth 20 ?

**Comment by harpalnain** [comment]
Check latest code updated for 20 depth data. I don't thinks you can get
tick data free of cost. Alphaventage api come with lots of other data items
like technical indicators but it is paid after trail period.

As per my knowledge i have shared all possible options.

One more possible solution could be embed javascript code in browser and
grep data and send it to serially to you application. This could be the
best free option.

One next level possible solution could be use session credential of open
session and send direct request to zerodha, but i don't know how to
make it work. If you find any possibility for that please let me know.

Harpal

**Comment by kiranmaya** [comment]
i'm not looking for free source,willing to pay for depth 20,already subscribed to kite Connect . share me your details ,will send some info regarding session .

**Comment by MLpranav** [comment]
@kiranmaya did you find how is kite streaming the 20 depth data? I tried the same analysis of websocket messages in developer tools and tried replicating in python, but only getting the 188 size 5 depth packets.

**Comment by kiranmaya** [comment]
@MLpranav 
Nope, unable to crack it, tried lots of ways, spent lots of time, forgot 20th depth data by websockets

**Comment by MLpranav** [comment]
@kiranmaya 
I found a different but decent source. Can't share here but feel free to connect on Discord `encounter78` if you still have need for it.
